apiVersion : apps/v1
kind: Deployment
metadata:
  name: shconnect-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shconnect-deployment
  template:
    metadata:
      labels:
        app: shconnect-deployment 
    spec:
      containers:
        - name: shconnect 
          image: kcscr.azurecr.io/kcskoteswaradoddajavahelloworldwebapp
          ports:
          - containerPort: 80
