apiVersion: v1 

kind: Service 

metadata: 

  name: shconnect-deployment 

spec: 

  selector: 

    app: shconnect-deployment 

  ports: 

    - protocol: TCP 

      port: 80 

      targetPort: 4443 

  #selector: 

    #run: shconnect-deployment 

  selector: 

    app: shconnect-deployment 

  selector: 

    app: shconnect-deployment 

  type: LoadBalancer 

 

I am giving targetPort: 4443 because our application will run on port 4443 locally so I am doing port forwarding to 80.
